---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: {{ .Values.nodePortHttp }}
  - port: 443
    name: https
    nodePort: {{ .Values.nodePortHttps }}
  - port: 22
    name: ssh
    nodePort: {{ .Values.nodePortSSH }}    
  selector:
    app: gitlab
          
